tunnel: PLACEHOLDER
credentials-file: /etc/cloudflared/credentials.json
no-autoupdate: true

ingress:
  - hostname: nextcloud.xbhl.online
    service: http://nextcloud:80
  - service: http_status:404
