include:
  - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v2.0.5
    inputs:
      vm-hostname: cloud.vm.xbhl.intranet
      vm-ssh-username: $SSH_USER
      vm-ssh-private-key: $SSH_PRIVATE_KEY
      service-name: nextcloud
      container-name: nextcloud
      container-location: /opt/containers/nextcloud
      cloudflare-dns-entry-name: nextcloud.xbhl.online
      cloudflare-dns-strategy: tunnel
      cloudflare-tunnel-uuid: $CLOUDFLARE_TUNNEL_UUID
      cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
      cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
      container-healthcheck-delay: 360
      delete-existing-container-files: true

test:nextcloud:docker-compose:
  before_script:
    - docker run --rm -v /tmp:/mnt alpine rm -rf /mnt/nextcloud-test-data
    - docker run --rm -v /tmp/nextcloud-test-data:/tmp/nextcloud-test-data alpine true
  variables:
    NEXTCLOUD_STORAGE_DRIVER_TYPE: "none"
    NEXTCLOUD_STORAGE_DRIVER_OPTS: "bind"
    NEXTCLOUD_STORAGE_DEVICE: "/tmp/nextcloud-test-data"

setup:generate-build-artifacts:
  script:
    - 'apk add --no-cache bash jq'
    - 'cp -r src/envs $BUILD_ARTIFACTS_DIR/'
    - 'cp -r src/cloudflared-config $BUILD_ARTIFACTS_DIR/'
    - './scripts/generate-cloudflare-tunnel-credentials.sh -t "$CLOUDFLARE_TUNNEL_TOKEN" -o $BUILD_ARTIFACTS_DIR/cloudflared-config/credentials.json'
    - 'sed -i "s|^tunnel:.*|tunnel: ${CLOUDFLARE_TUNNEL_UUID}|" $BUILD_ARTIFACTS_DIR/cloudflared-config/config.yml'
    - 'sed -i "s|^NEXTCLOUD_MAIN_USER=.*|NEXTCLOUD_MAIN_USER=${NEXTCLOUD_MAIN_USER:-lbarczynski}|" $BUILD_ARTIFACTS_DIR/envs/nextcloud.env'
    - 'sed -i "s|^NEXTCLOUD_ADMIN_PASSWORD=.*|NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}|" $BUILD_ARTIFACTS_DIR/envs/nextcloud.env'
    - 'sed -i "s|^POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}|" $BUILD_ARTIFACTS_DIR/envs/db.env'
    - 'sed -i "s|^REDIS_HOST_PASSWORD=.*|REDIS_HOST_PASSWORD=${NEXTCLOUD_REDIS_PASSWORD}|" $BUILD_ARTIFACTS_DIR/envs/redis.env'
    - 'sed -i "s|^OIDC_CLIENT_SECRET=.*|OIDC_CLIENT_SECRET=${NEXTCLOUD_OAUTH_CLIENT_SECRET}|" $BUILD_ARTIFACTS_DIR/envs/oidc.env'
    - 'sed -i "s|^OPENAI_API_KEY=.*|OPENAI_API_KEY=${OPEN_WEBUI_API_KEY}|" $BUILD_ARTIFACTS_DIR/envs/ai.env'
    - 'sed -i "s|^SMTP_HOST=.*|SMTP_HOST=${SMTP_HOST}|" $BUILD_ARTIFACTS_DIR/envs/smtp.env'
    - 'sed -i "s|^SMTP_PORT=.*|SMTP_PORT=${SMTP_PORT}|" $BUILD_ARTIFACTS_DIR/envs/smtp.env'
    - 'sed -i "s|^SMTP_USERNAME=.*|SMTP_USERNAME=${SMTP_USERNAME}|" $BUILD_ARTIFACTS_DIR/envs/smtp.env'
    - 'sed -i "s|^SMTP_PASSWORD=.*|SMTP_PASSWORD=${SMTP_PASSWORD}|" $BUILD_ARTIFACTS_DIR/envs/smtp.env'
    - 'sed -i "s|^SMTP_FROM=.*|SMTP_FROM=${SMTP_FROM}|" $BUILD_ARTIFACTS_DIR/envs/smtp.env'
    - 'sed -i "s|^COTURN_SECRET=.*|COTURN_SECRET=${NEXTCLOUD_COTURN_SECRET}|" $BUILD_ARTIFACTS_DIR/envs/talk.env'
    - 'sed -i "s|^LDAP_AGENT_PASSWORD=.*|LDAP_AGENT_PASSWORD=${LDAP_PASSWORD}|" $BUILD_ARTIFACTS_DIR/envs/ldap.env'

deploy:nextcloud:update-coturn-dns:
  stage: deploy
  image: alpine:3.24.1
  needs:
    - "deploy:nextcloud:start-service"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  variables:
    DNS_RECORD_TYPE: "A"
    DNS_TTL: 120
    DNS_PROXIED: "false"
    CLOUDFLARE_DNS_ENTRY_NAME: "talk.nextcloud.xbhl.online"
  before_script:
    - apk add --no-cache curl jq
  script:
    - 'export DNS_CONTENT=$(curl -s https://api.ipify.org || curl -s https://ifconfig.me || curl -s https://icanhazip.com)'
    - 'echo "Resolved public router IP for Coturn: $DNS_CONTENT"'
    - !reference [.cloudflare-update-script, script]
