services:
  collabora:
    build: .
    image: collabora/code:26.04.4.1.1
    container_name: collabora
    labels:
      - 'wud.watch=true'
      - 'wud.display.name=Collabora Online'
      - 'wud.display.icon=si:collaboraonline'
      - 'wud.tag.include=^\d+\.\d+\.\d+\.\d+\.\d+$$'
      - "wud.link.template=https://www.collaboraonline.com/code-release-notes/"
    env_file:
      - envs/collabora.env
    environment:
      aliasgroup1: "https://nextcloud.xbhl.online:443"
      extra_params: "--o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false --o:net.proto=IPv4"
      server_name: "office.xbhl.online"
      dictionaries: "pl_PL en_US en_GB"
    cap_add:
      - MKNOD
      - SYS_ADMIN
    networks:
      - collabora_internal
    healthcheck:
      test: [ "CMD", "/usr/bin/wget", "-q", "-O", "-", "http://127.0.0.1:9980/hosting/discovery" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:2026.9.1
    container_name: collabora_cloudflared
    labels:
      - 'wud.watch=true'
      - 'wud.display.name=Cloudflared'
      - 'wud.display.icon=si:cloudflare'
      - 'wud.tag.include=^\d{4}\.\d+\.\d+$$'
      - "wud.link.template=https://github.com/cloudflare/cloudflared/releases/tag/$${major}.$${minor}.$${patch}"
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared-config:/etc/cloudflared:ro
    networks:
      - collabora_internal
    depends_on:
      collabora:
        condition: service_healthy
    restart: unless-stopped

networks:
  collabora_internal:
    name: collabora_internal_network
