services:
  go-vod:
    image: radialapps/go-vod:latest
    container_name: nextcloud_go_vod
    hostname: nextcloud-go-vod.ctr.xbhl.intranet
    init: true
    networks:
      - proxy
    ports:
      - "47788:47788"
    environment:
      - TZ=Europe/Warsaw
      - NEXTCLOUD_HOST=https://nextcloud.xbhl.online
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /share/RemoteStorage/NextCloud:/var/nc-data:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-go-vod.rule=Host(`${GO_VOD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-go-vod.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-go-vod.tls=true"
      - "traefik.http.routers.nextcloud-go-vod.service=nextcloud-go-vod"
      - "traefik.http.services.nextcloud-go-vod.loadbalancer.server.port=47788"
      - "traefik.docker.network=proxy"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -o /dev/null http://127.0.0.1:47788/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  proxy:
    external: true
