source_directories:
  - /var/www/html
  - /var/www/html/data

repositories:
  - path: /mnt/backup/repo
    label: nfs_backup_repo

retention:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
  keep_yearly: 1

consistency:
  checks:
    - repository
    - archives
  check_last: 3

postgresql_databases:
  - name: ${POSTGRES_DB}
    hostname: postgres_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    format: custom
